spring:
  main:
    allow-circular-references: true
  profiles:
    active: "dev"

  # Naming strategy
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      default_schema: public
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: create
    generate-ddl: false

    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true

    # Show or not log for each sql query
    show-sql: true
  #    defer-datasource-initialization: false

  #  sql:
  #    init:
  #      mode: always



  #  cache:
  #    type: redis
  #    redis:
  #      time-to-live: 36000
  #      key-prefix: anissa

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    #    com.zaxxer.hikari: TRACE
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    io.grpc: DEBUG


springdoc:
  api-docs:
    path: /api-docs
  enable-native-support: true
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method

jwt:
  secret: b1z0ne
  expirationInMs: 864000000


docker:
  publishRegistry:

#grpc:
#  server:
#    port: 8080

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db-bizonev2-do-user-6486567-0.b.db.ondigitalocean.com:25061/test-native-pool?searchpath=public&createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Bangkok&prepareThreshold=0
    username: doadmin
    password: AVNS_DYaUIJcl6eFII-CTOk7
    hikari:
      schema: public
      connectionTimeout: 30000
      leakDetectionThreshold: 120000